### ISSUE TITLE
The big picture

### ISSUE THREAD

**Issue by valentinogagliardi** [tom-186/CSharpExercises#9]
Now that you have all the classes in place, in `Program.Main`, write the logic to fullfill the following requirements:

### Milestone 1

- [x] we can create new customers
- [x] we can create new articles
- [x] we can add each article to `Articles`
- [x] we can list all the articles (printing to console is enough)

### Milestone 2

- [x] we can search for an article by its description, and we can print its price
- [x] we can add the searched article to the Cart

### Milestone 3

- [x] we can add multiple articles to the cart
- [x] we can provide the user with a total price of all the articles in the cart

Hints: `List` methods - `foreach` - LINQ

```csv
0, 300, 609, 228, 1
1, 301, 610, 307, 3
2, 302, 611, 16, 1
3, 303, 612, 193, 2
4, 304, 613, 325, 4
5, 305, 614, 339, 1
6, 306, 615, 96, 2
7, 307, 616, 88, 4
8, 308, 617, 77, 3
9, 309, 618, 180, 2
10, 310, 619, 272, 4
11, 311, 620, 337, 2
12, 312, 621, 65, 3
13, 313, 622, 146, 1
14, 314, 623, 285, 3
15, 315, 624, 234, 4
16, 316, 625, 102, 3
17, 317, 626, 286, 1
18, 318, 627, 129, 3
19, 319, 628, 104, 2
```
